from __future__ import annotations

import textwrap
from pathlib import Path
from typing import List

from .tracker import ExecutionRecord

_HEADER_TEMPLATE = """\
# Generated by jupytertracker (sequential mode)
# Total execution time: {total_time}
# Cells recorded: {cell_count}
#
# Each block below reflects exactly what ran, in the order it ran.
# A cell that was modified and re-run appears multiple times — once per execution.
# NOTE: This script may not run top-to-bottom without error if cells relied on
# intermediate kernel state not captured here. It is an execution record, not a
# guaranteed reproducible script.
"""


def _fmt_duration(seconds: float) -> str:
    """Human-readable duration: '34ms', '1.23s', '2m 5.1s'."""
    if seconds < 1:
        return f"{seconds * 1000:.0f}ms"
    if seconds < 60:
        return f"{seconds:.2f}s"
    mins = int(seconds // 60)
    secs = seconds % 60
    return f"{mins}m {secs:.1f}s"


def export_sequential(log: List[ExecutionRecord], path: str | Path) -> None:
    """Write the raw execution log to a .py file, one block per execution."""
    if not log:
        header = _HEADER_TEMPLATE.format(total_time="0ms", cell_count=0)
        Path(path).write_text(header + "# No cells were recorded.\n", encoding="utf-8")
        return

    total_seconds = sum(r.duration for r in log)
    header = _HEADER_TEMPLATE.format(
        total_time=_fmt_duration(total_seconds),
        cell_count=len(log),
    )

    blocks = [header]
    for record in log:
        source = record.source.rstrip("\n")
        comment = _magic_comment(source)
        timing = _fmt_duration(record.duration)
        block = f"# execution {record.exec_count}  [{timing}]\n{comment}{source}\n"
        blocks.append(block)

    Path(path).write_text("\n".join(blocks) + "\n", encoding="utf-8")


def _magic_comment(source: str) -> str:
    first_line = source.lstrip().split("\n")[0]
    if first_line.startswith("%") or first_line.startswith("!"):
        return "# magic/shell command — requires Jupyter environment to run as-is\n"
    return ""
