from __future__ import annotations

import textwrap
from pathlib import Path
from typing import List

from .tracker import ExecutionRecord

_HEADER = """\
# Generated by jupytertracker (sequential mode)
# Each block below reflects exactly what ran, in the order it ran.
# A cell that was modified and re-run appears multiple times — once per execution.
# NOTE: This script may not run top-to-bottom without error if cells relied on
# intermediate kernel state not captured here. It is an execution record, not a
# guaranteed reproducible script. Use mode='dedup' (v2) for deduplication.
"""


def export_sequential(log: List[ExecutionRecord], path: str | Path) -> None:
    """Write the raw execution log to a .py file, one block per execution."""
    if not log:
        Path(path).write_text(_HEADER + "# No cells were recorded.\n", encoding="utf-8")
        return

    blocks = [_HEADER]
    for record in log:
        source = record.source.rstrip("\n")
        comment = _magic_comment(source)
        block = f"# execution {record.exec_count}\n{comment}{source}\n"
        blocks.append(block)

    Path(path).write_text("\n".join(blocks) + "\n", encoding="utf-8")


def _magic_comment(source: str) -> str:
    first_line = source.lstrip().split("\n")[0]
    if first_line.startswith("%") or first_line.startswith("!"):
        return "# magic/shell command — requires Jupyter environment to run as-is\n"
    return ""
